export const problem1Data = [
  { id: 0, name: "A", status: "active" },
  { id: 1, name: "B", status: "completed" },
  { id: 2, name: "C", status: "archive" },
  { id: 3, name: "D", status: "active" },
  { id: 4, name: "E", status: "completed" },
  { id: 5, name: "F", status: "active" },
  { id: 6, name: "G", status: "active" },
  { id: 7, name: "H", status: "completed" },
  { id: 8, name: "I", status: "pending" },
  { id: 9, name: "J", status: "active" },
  { id: 10, name: "K", status: "archive" },
  { id: 11, name: "L", status: "completed" },
  { id: 12, name: "M", status: "pending" },
  { id: 13, name: "N", status: "archive" },
  { id: 14, name: "O", status: "completed" },
  { id: 15, name: "P", status: "pending" },
  { id: 16, name: "Q", status: "active" },
  { id: 17, name: "R", status: "active" },
  { id: 18, name: "S", status: "completed" },
  { id: 19, name: "T", status: "archive" },
  { id: 20, name: "U", status: "active" },
  { id: 21, name: "V", status: "completed" },
  { id: 22, name: "W", status: "active" },
  { id: 23, name: "X", status: "active" },
  { id: 24, name: "Y", status: "pending" },
  { id: 25, name: "Z", status: "pending" },
];
